# Generated by Django 4.0.6 on 2022-07-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERC20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('chain_id', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoolAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_tier', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=256)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.networks')),
                ('token0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token0', to='events.erc20')),
                ('token1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token1', to='events.erc20')),
            ],
        ),
        migrations.CreateModel(
            name='ERC20Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('ERC20', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.erc20')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.networks')),
            ],
        ),
    ]
