# Generated by Django 4.0.6 on 2022-07-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erc20',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='networks',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='erc20addresses',
            unique_together={('ERC20', 'network')},
        ),
        migrations.AlterUniqueTogether(
            name='pooladdresses',
            unique_together={('token0', 'token1', 'fee_tier', 'network')},
        ),
    ]
