# Generated by Django 4.0.6 on 2022-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_erc20_symbol_alter_networks_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networks',
            name='short',
            field=models.CharField(default=None, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
