# Generated by Django 4.0.6 on 2022-07-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_swapevent_erc20_decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapevent',
            name='amount0',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='amount1',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='liquidity',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='sqrtPriceX96',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='tick',
            field=models.BigIntegerField(),
        ),
    ]
