# Generated by Django 4.0.6 on 2022-07-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_swapevent_amount0_alter_swapevent_amount1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapevent',
            name='amount0',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='amount1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='liquidity',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='sqrtPriceX96',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='tick',
            field=models.CharField(max_length=256),
        ),
    ]
