# Generated by Django 4.0.6 on 2022-07-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_swapevent_amount0_alter_swapevent_amount1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networks',
            name='chain_id',
            field=models.IntegerField(null=True),
        ),
    ]
