# Generated by Django 4.0.6 on 2022-07-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_networks_chain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapevent',
            name='sqrtPriceX96',
            field=models.CharField(max_length=100),
        ),
    ]
