# Generated by Django 4.0.6 on 2022-07-16 11:08

from django.db import migrations
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_swapevent_sqrtpricex96'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapevent',
            name='amount0',
            field=events.models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='amount1',
            field=events.models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='liquidity',
            field=events.models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='tick',
            field=events.models.BigIntegerField(),
        ),
    ]
