# Generated by Django 4.0.6 on 2022-07-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_swapevent_amount0_alter_swapevent_amount1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapevent',
            name='amount0',
            field=models.DecimalField(decimal_places=0, max_digits=77),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='amount1',
            field=models.DecimalField(decimal_places=0, max_digits=77),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='liquidity',
            field=models.DecimalField(decimal_places=0, max_digits=77),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='tick',
            field=models.DecimalField(decimal_places=0, max_digits=77),
        ),
    ]
