# Generated by Django 4.0.6 on 2022-07-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_swapevent_amount0_alter_swapevent_amount1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapevent',
            name='pool_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='events.pooladdresses'),
            preserve_default=False,
        ),
    ]
