# Generated by Django 4.0.6 on 2022-07-18 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_swapevent_pool_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('blockHash', models.CharField(max_length=256)),
                ('blockNumber', models.BigIntegerField()),
                ('data', models.TextField()),
                ('logIndex', models.BigIntegerField()),
                ('removed', models.CharField(max_length=256)),
                ('topics', models.CharField(max_length=256)),
                ('transactionHash', models.CharField(max_length=256)),
                ('transactionIndex', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='swapevent',
            name='transaction_meta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.transactionmeta'),
        ),
    ]
