# Generated by Django 4.0.6 on 2022-07-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_transactionmeta_swapevent_transaction_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockNumber', models.BigIntegerField()),
                ('blockHash', models.CharField(max_length=256)),
                ('timestamp', models.DecimalField(decimal_places=0, max_digits=77)),
                ('datetime', models.DateTimeField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.networks')),
            ],
        ),
    ]
