# Generated by Django 4.0.6 on 2022-07-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_blocktimes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactionmeta',
            index=models.Index(fields=['blockNumber'], name='events_tran_blockNu_de0c24_idx'),
        ),
    ]
